# YOLOv11 Configuration for Object Detection

# Parameters
nc: 1  # Number of classes (modify based on your dataset)

scales:
  # [depth_multiple, width_multiple, max_channels]
  # n: [0.50, 0.25, 1024]   # nano
  s: [0.33, 0.50, 1024]   # small
  # m: [0.67, 0.75, 1024]    # medium
  # l: [1.00, 1.00, 512]    # large
  # x: [1.00, 1.25, 512]    # xlarge

# Backbone
backbone:
  # YOLOv11 Feature Extraction
  - [-1, 1, Conv, [64, 3, 2]]              # 0: P1/2 - Initial conv layer
  - [-1, 1, Conv, [128, 3, 2]]             # 1: P2/4 - Downsample
  - [-1, 2, C2f, [128, True]]              # 2: P2 - C2f block with residual connection
  - [-1, 1, Conv, [256, 3, 2]]             # 3: P3/8 - Downsample
  - [-1, 2, C2f, [256, True]]              # 4: P3 - C2f block (to head)
  - [-1, 1, Conv, [512, 3, 2]]             # 5: P4/16 - Downsample
  - [-1, 2, C2f, [512, True]]              # 6: P4 - C2f block (to head)
  - [-1, 1, Conv, [1024, 3, 2]]            # 7: P5/32 - Downsample
  - [-1, 2, C2f, [1024, True]]             # 8: P5 - C2f block (to head)
  - [-1, 1, SPPF, [1024, 5]]               # 9: SPPF - Spatial Pyramid Pooling Fast

# Head
head:
  # YOLOv11 Detection Head with PANet structure
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]     # 10: Upsample P5
  - [[-1, 6], 1, Concat, [1]]                      # 11: Concat upsampled P5 with P4
  - [-1, 2, C2f, [512, False]]                     # 12: C2f fusion block
  
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]     # 13: Upsample 
  - [[-1, 4], 1, Concat, [1]]                      # 14: Concat with P3
  - [-1, 2, C2f, [256, False]]                     # 15: C2f fusion block (to detect)
  
  - [-1, 1, Conv, [256, 3, 2]]                     # 16: Downsample
  - [[-1, 12], 1, Concat, [1]]                     # 17: Concat with P4 level
  - [-1, 2, C2f, [512, False]]                     # 18: C2f fusion block (to detect)
  
  - [-1, 1, Conv, [512, 3, 2]]                     # 19: Downsample
  - [[-1, 9], 1, Concat, [1]]                      # 20: Concat with P5 level
  - [-1, 2, C2f, [1024, False]]                    # 21: C2f fusion block (to detect)
  
  # Detection layers
  - [[15, 18, 21], 1, Detect, [nc]]                # 22: Detect layer for 3 scales

# Training Hyperparameters
training:
  task: detect
  epochs: 200
  batch: 64
  optimizer: SGD
  lr0: 0.01                 # Learning rate iniziale per AdamW
  lrf: 0.0001                # Fattore per learning rate finale (lr0 * lrf)
  weight_decay: 0.0005         # Decadimento del peso (valore da paper YOLOv12)
  warmup_epochs: 3           # Epochs di warmup per lr
  pretrained: False
  save_period: 10
  cache: False
  save: True
  verbose: True
  save_dir: "/app/results"
  device: 0
  project: "/app/results"